-- MySQL Script generated by MySQL Workbench
-- Tue May  2 17:24:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mkpartnairtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mkpartnairtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkpartnairtest` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mkpartnairtest` ;

-- -----------------------------------------------------
-- Table `mkpartnairtest`.`aircraft_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`aircraft_type` (
  `id` INT NOT NULL,
  `type_en` VARCHAR(255) NOT NULL,
  `type_fr` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type_en` ASC),
  UNIQUE INDEX `type_fr_UNIQUE` (`type_fr` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`manufacturer` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `flag` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`aircraft_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`aircraft_category` (
  `id` INT NOT NULL,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`aircraft_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`aircraft_description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_en` TEXT NOT NULL,
  `content_fr` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`aircraft_crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`aircraft_crew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `crew_fr` VARCHAR(255) NOT NULL,
  `crew_en` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`fleet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`fleet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(255) NOT NULL,
  `passengers` INT NULL,
  `cruise_speed` INT NULL,
  `aircraft_range` INT NULL,
  `photo_picto` VARCHAR(255) NULL,
  `photo_exter` VARCHAR(255) NULL,
  `photo_inter` VARCHAR(255) NULL,
  `photo_plan` VARCHAR(255) NULL,
  `photo_bonus` VARCHAR(255) NULL,
  `aircraft_type_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `aircraft_category_id` INT NOT NULL,
  `aircraft_description_id` INT NOT NULL,
  `aircraft_crew_id` INT NOT NULL,
  PRIMARY KEY (`id`, `aircraft_type_id`, `manufacturer_id`, `aircraft_category_id`, `aircraft_description_id`, `aircraft_crew_id`),
  INDEX `fk_fleet_aircraft_type_idx` (`aircraft_type_id` ASC),
  INDEX `fk_fleet_manufacturer1_idx` (`manufacturer_id` ASC),
  INDEX `fk_fleet_aircraft_category1_idx` (`aircraft_category_id` ASC),
  INDEX `fk_fleet_aircraft_description1_idx` (`aircraft_description_id` ASC),
  INDEX `fk_fleet_aircraft_crew1_idx` (`aircraft_crew_id` ASC),
  CONSTRAINT `fk_fleet_aircraft_type`
    FOREIGN KEY (`aircraft_type_id`)
    REFERENCES `mkpartnairtest`.`aircraft_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `mkpartnairtest`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_aircraft_category1`
    FOREIGN KEY (`aircraft_category_id`)
    REFERENCES `mkpartnairtest`.`aircraft_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_aircraft_description1`
    FOREIGN KEY (`aircraft_description_id`)
    REFERENCES `mkpartnairtest`.`aircraft_description` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fleet_aircraft_crew1`
    FOREIGN KEY (`aircraft_crew_id`)
    REFERENCES `mkpartnairtest`.`aircraft_crew` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departue` VARCHAR(255) NOT NULL,
  `arrival` VARCHAR(255) NOT NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL,
  `price` INT NOT NULL,
  `fleet_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fleet_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sale_fleet1_idx` (`fleet_id` ASC),
  CONSTRAINT `fk_sale_fleet1`
    FOREIGN KEY (`fleet_id`)
    REFERENCES `mkpartnairtest`.`fleet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(400) NULL,
  `password` VARCHAR(400) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `last_connection` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`article_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`article_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_en` VARCHAR(255) NOT NULL,
  `category_fr` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`article_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`article_title` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_en` VARCHAR(500) NOT NULL,
  `title_fr` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`article_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`article_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_en` TEXT NOT NULL,
  `content_fr` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkpartnairtest`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkpartnairtest`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(500) NULL,
  `article_date` DATE NOT NULL,
  `picture_1` VARCHAR(500) NULL,
  `picture_2` VARCHAR(500) NULL,
  `article_category_id` INT NOT NULL,
  `article_title_id` INT NOT NULL,
  `article_content_id` INT NOT NULL,
  PRIMARY KEY (`id`, `article_category_id`, `article_title_id`, `article_content_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_article_article_category1_idx` (`article_category_id` ASC),
  INDEX `fk_article_article_title1_idx` (`article_title_id` ASC),
  INDEX `fk_article_article_content1_idx` (`article_content_id` ASC),
  CONSTRAINT `fk_article_article_category1`
    FOREIGN KEY (`article_category_id`)
    REFERENCES `mkpartnairtest`.`article_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_article_title1`
    FOREIGN KEY (`article_title_id`)
    REFERENCES `mkpartnairtest`.`article_title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_article_content1`
    FOREIGN KEY (`article_content_id`)
    REFERENCES `mkpartnairtest`.`article_content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
